---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-assistant
spec:
  interval: 2h
  ref:
    branch: main
  url: https://github.com/josephtfox/home-assistant-kustomize.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  interval: 4h
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-assistant
    namespace: home-assistant
  targetNamespace: home-assistant
# To use hostpath storage uncomment the line below
#  patches:
#    - patch: |
#        - op: add
#          path: /spec/template/spec/volumes/-
#          value:
#            name: home-assistant
#            hostPath:
#              path: /config
#        - op: add
#          path: /spec/template/spec/containers/0/volumeMounts/-
#          value:
#            name: home-assistant
#            mountPath: /data/home-assistant/
#            type: DirectoryOrCreate
#      target:
#        kind: StatefulSet
#        name: home-assistant
