apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.x.x
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: stable
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: home-assistant.your-domain.com
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        storageClass: "your-storage-class"
        accessMode: ReadWriteOnce
        size: 1Gi
