kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
    kubernetes.io/name: home-assistant
spec:
  ports:
    - name: home-assistant
      protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30438
  selector:
    app: home-assistant
  type: NodePort
  sessionAffinity: None
