apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lower-base
  namespace: apps
spec:
  interval: 1m
  url: https://github.com/josephtfox/sample-maven-app
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lower-base
  namespace: apps
spec:
  serviceAccountName: lower-base
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: lower-base
  prune: true
