apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 5m
  url: https://github.com/dani-garcia/vaultwarden
  ref:
    branch: main
