apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: metallb/metallb
      sourceRef:
        kind: HelmRepository
        name: metallb # Matches the HelmRepository name.
      version: 0.14.9 # Use a stable version.
  values:
    controller:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
