---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml=flux-kube-state-metrics-config.yaml
generatorOptions:
  disableNameSuffixHash: true
