apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tomcat
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/production/tomcat"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: tomcat
