apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: '>=5.0.0 <6.0.0'
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: vaultwarden.yourdomain.com
            paths:
              - path: /
                pathType: Prefix
