apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: ghcr.io/josephtfox/tomcat-root-war:v1.0.1
        ports:
        - containerPort: 8080
