apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arc
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/production/arc
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-controllers
  timeout: 2m
