apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik.yaml
  - svc.yaml
  - rbac.yaml
  - ingressroute.yaml

configMapGenerator:
  - name: traefik
    files:
      - values.yaml

namespace: traefik
