# Enable Traefik as the default IngressClass
ingressClass:
  enabled: true
  isDefaultClass: true

# EntryPoints define the ports Traefik will listen on
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# CertificatesResolvers for Let's Encrypt (via cert-manager)
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      storage: /data/acme.json
      tlsChallenge: {}

# Enable the Traefik dashboard
dashboard:
  enabled: true
  ingressRoute:
    entryPoints:
      - websecure
    annotations:
      kubernetes.io/ingress.class: "traefik"
    auth:
      basic:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" # Replace with your credentials

# Enable Kubernetes CRD provider
providers:
  kubernetesCRD:
    enabled: true

# Enable Kubernetes Ingress provider
providers:
  kubernetesIngress:
    enabled: true

# Logs configuration
logs:
  general:
    level: INFO

# Enable metrics (optional)
metrics:
  prometheus:
    enabled: true

# Additional arguments (optional)
additionalArguments:
  - "--log.level=INFO"
